pipeline {
    agent {
        docker {
            image '15.0.1-alpine3.10'
            args '-p 3000:3000'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
    }
} 